{% set name = "winflexbison" %}
{% set version = "2.5.23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/lexxmark/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 445bd1bcb90e0c84e97f6e44de76869f8e778c60ddbd7c39a7b2142f8ba43e61
    patches:
      - fix-install.patch

build:
  number: 0
  skip: true  # [not win or vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
    - cmake

test:
  commands:
    - win_bison.exe --version
    - win_flex.exe --version

about:
  home: https://github.com/lexxmark/winflexbison
  license: GPL-3.0
  license_family: GPL
  license_file:
    - bison/src/COPYING
    - flex/src/COPYING
  summary: |
    WinFlexBison is a Windows port of Flex (the fast lexical analyser) and GNU Bison (parser generator).

extra:
  recipe-maintainers:
    - seanyen
