{% set name = "winflexbison" %}
{% set version = "2.5.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/lexxmark/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 697c2c4af3308625605b75498bd63a9a294660f8e43a4c35452cf4334fa4a530
    patches:
      - fix-install.patch

build:
  number: 1
  skip: true  # [not win or vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
    - cmake

test:
  files:
    - bare-minimum.y
  commands:
    - win_bison.exe --version
    - win_bison.exe bare-minimum.y
    - win_flex.exe --version

about:
  home: https://github.com/lexxmark/winflexbison
  license: GPL-3.0
  license_family: GPL
  license_file:
    - bison/src/COPYING
    - flex/src/COPYING
  summary: |
    WinFlexBison is a Windows port of Flex (the fast lexical analyser) and GNU Bison (parser generator).

extra:
  recipe-maintainers:
    - seanyen
